# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Operação Serenata de Amor
tagline:             Robôs contra a corrupção
url:                 https://serenatadeamor.org
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Data Science Brigade
  url:               https://www.facebook.com/operacaoSerenataDeAmor
  email:             contato@datasciencebr.com

# Custom vars
version:             1.0.0
github:
  repo:             https://github.com/datasciencebr/serenata-website

#i18n
gems:
                    - jekyll-multiple-languages-plugin
languages:          ["pt-br", "en"]
exclude_from_localizations: ["javascript", "css"]
